const CLIENT_SERVER_INVITE_PATH = '/app/invite/';
const CLIENT_EMAIL_VERIFICATION_PATH = '/verify-email';
const CLIENT_RESET_PASSWORD_PATH = '/reset-password';

export {
  CLIENT_SERVER_INVITE_PATH,
  CLIENT_EMAIL_VERIFICATION_PATH,
  CLIENT_RESET_PASSWORD_PATH,
};
